### ISSUE TITLE
Interface polishing

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-ui#45]
A few things to polish before the first release:

- [x] Global settings needs a border.
- [x] Capitalize individual words of group box labels.
- [x] Units.
  
In Liggghts settings:

- [x] Flow particles fixed: Fix flow particles / Fix wall particles 
- [x] System parameters/ conditions. Add a space between parameters and the slash
- [x] reposition the Wall particles parameters to the side.
- [x] keep consistent order between flow and wall in the particles parameters.
- [x] Disable the run button if any value is missing or incorrect.

In Openfoam settings
- [x] Boundary conditions label should be a groupbox label.
- [x] Reposition / in system parameters groupbox label.
- [x] Try to remove the double groupbox for channel size and number of elements. Not sure of a better way. Try however to shorten the "number of elements in channel directions" label.
- [x] In the tab internal widget, add a groupbox border.
- [x] Put on the same line the type for the pressure/velocity boundary conditions and the values, when present. This will also remove the box border.
- [x] Change the radio buttons to a combobox.

**Comment by martinRenou** [comment]
Concerning units, it seams like TraitsUI does not provide any attribute to set a unit to a trait. Should I put the unit in the label ? 

"Timestep (s): 1e-06"

**Comment by stefanoborini** [comment]
Timestep (s) is fine.
